import os

class Config:
    ADMIN_DB_USER: str = os.getenv("ADMIN_DB_USER")
    ADMIN_DB_PASSWORD: str = os.getenv("ADMIN_DB_PASSWORD")
    ADMIN_DB_NAME: str = os.getenv("ADMIN_DB_NAME")
    ADMIN_DB_HOST: str = os.getenv("ADMIN_DB_HOST")
    ADMIN_DB_REAL_HOST: str = os.getenv("ADMIN_DB_REAL_HOST")
    ADMIN_DATABASE_URL: str = f"postgresql://{ADMIN_DB_USER}:{ADMIN_DB_PASSWORD}@{ADMIN_DB_HOST}:5432/{ADMIN_DB_NAME}"
    ADMIN_DATABASE_REAL_URL: str = f"postgresql://{ADMIN_DB_USER}:{ADMIN_DB_PASSWORD}@{ADMIN_DB_REAL_HOST}:5432/{ADMIN_DB_NAME}"
    
    REGISTIRATION_DB_USER: str = os.getenv("REGISTIRATION_DB_USER")
    REGISTIRATION_DB_PASSWORD: str = os.getenv("REGISTIRATION_DB_PASSWORD")
    REGISTIRATION_DB_NAME: str = os.getenv("REGISTIRATION_DB_NAME")
    REGISTIRATION_DB_HOST: str = os.getenv("REGISTIRATION_DB_HOST")
    REGISTIRATION_DB_REAL_HOST: str = os.getenv("REGISTIRATION_DB_REAL_HOST")
    REGISTIRATION_DATABASE_URL: str = f"postgresql://{REGISTIRATION_DB_USER}:{REGISTIRATION_DB_PASSWORD}@{REGISTIRATION_DB_HOST}:5432/{REGISTIRATION_DB_NAME}"
    REGISTIRATION_DATABASE_REAL_URL: str = f"postgresql://{REGISTIRATION_DB_USER}:{REGISTIRATION_DB_PASSWORD}@{REGISTIRATION_DB_REAL_HOST}:5432/{REGISTIRATION_DB_NAME}"
    
    AYGIT_DB_USER: str = os.getenv("AYGIT_DB_USER")
    AYGIT_DB_PASSWORD: str = os.getenv("AYGIT_DB_PASSWORD")
    AYGIT_DB_NAME: str = os.getenv("AYGIT_DB_NAME")
    AYGIT_DB_HOST: str = os.getenv("AYGIT_DB_HOST")
    AYGIT_DB_REAL_HOST: str = os.getenv("AYGIT_DB_REAL_HOST")
    AYGIT_DATABASE_URL: str = f"postgresql://{AYGIT_DB_USER}:{AYGIT_DB_PASSWORD}@{AYGIT_DB_HOST}:5432/{AYGIT_DB_NAME}"
    AYGIT_DATABASE_REAL_URL: str = f"postgresql://{AYGIT_DB_USER}:{AYGIT_DB_PASSWORD}@{AYGIT_DB_REAL_HOST}:5432/{AYGIT_DB_NAME}"

    NET_GSM_USER: str = os.getenv("NET_GSM_USER")
    NET_GSM_PASSWORD: str = os.getenv("NET_GSM_PASSWORD")

    JWT_SECRET: str = os.getenv("JWT_SECRET")
    NOREPLY_EMAIL: str = os.getenv("NOREPLY_EMAIL")
    NOREPLY_PASSWORD: str = os.getenv("NOREPLY_PASSWORD")
    ENVIRONMENT: str = os.getenv("ENVIRONMENT")